# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/cap_touch_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CapTouchDialog(object):
    def setupUi(self, CapTouchDialog):
        CapTouchDialog.setObjectName("CapTouchDialog")
        CapTouchDialog.resize(575, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CapTouchDialog.sizePolicy().hasHeightForWidth())
        CapTouchDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(CapTouchDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bc2 = QtWidgets.QWidget(CapTouchDialog)
        self.bc2.setStyleSheet("")
        self.bc2.setObjectName("bc2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.bc2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.bc2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.b21 = QtWidgets.QLabel(self.bc2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.b21.setFont(font)
        self.b21.setStyleSheet("background-color: white;")
        self.b21.setAlignment(QtCore.Qt.AlignCenter)
        self.b21.setObjectName("b21")
        self.horizontalLayout_3.addWidget(self.b21)
        self.b22 = QtWidgets.QLabel(self.bc2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.b22.setFont(font)
        self.b22.setStyleSheet("background-color: white;")
        self.b22.setAlignment(QtCore.Qt.AlignCenter)
        self.b22.setObjectName("b22")
        self.horizontalLayout_3.addWidget(self.b22)
        self.b23 = QtWidgets.QLabel(self.bc2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.b23.setFont(font)
        self.b23.setStyleSheet("background-color: white;")
        self.b23.setAlignment(QtCore.Qt.AlignCenter)
        self.b23.setObjectName("b23")
        self.horizontalLayout_3.addWidget(self.b23)
        self.b24 = QtWidgets.QLabel(self.bc2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.b24.setFont(font)
        self.b24.setStyleSheet("background-color: white;")
        self.b24.setAlignment(QtCore.Qt.AlignCenter)
        self.b24.setObjectName("b24")
        self.horizontalLayout_3.addWidget(self.b24)
        self.b25 = QtWidgets.QLabel(self.bc2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.b25.setFont(font)
        self.b25.setStyleSheet("background-color: white;")
        self.b25.setAlignment(QtCore.Qt.AlignCenter)
        self.b25.setObjectName("b25")
        self.horizontalLayout_3.addWidget(self.b25)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.setStretch(1, 1)
        self.verticalLayout.addWidget(self.bc2)
        self.bc1 = QtWidgets.QWidget(CapTouchDialog)
        self.bc1.setStyleSheet("")
        self.bc1.setObjectName("bc1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.bc1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.bc1)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b11 = QtWidgets.QLabel(self.bc1)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.b11.setFont(font)
        self.b11.setStyleSheet("background-color: white;")
        self.b11.setAlignment(QtCore.Qt.AlignCenter)
        self.b11.setObjectName("b11")
        self.horizontalLayout.addWidget(self.b11)
        self.b12 = QtWidgets.QLabel(self.bc1)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.b12.setFont(font)
        self.b12.setStyleSheet("background-color: white;")
        self.b12.setAlignment(QtCore.Qt.AlignCenter)
        self.b12.setObjectName("b12")
        self.horizontalLayout.addWidget(self.b12)
        self.b13 = QtWidgets.QLabel(self.bc1)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.b13.setFont(font)
        self.b13.setStyleSheet("background-color: white;")
        self.b13.setAlignment(QtCore.Qt.AlignCenter)
        self.b13.setObjectName("b13")
        self.horizontalLayout.addWidget(self.b13)
        self.b14 = QtWidgets.QLabel(self.bc1)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.b14.setFont(font)
        self.b14.setStyleSheet("background-color: white;")
        self.b14.setAlignment(QtCore.Qt.AlignCenter)
        self.b14.setObjectName("b14")
        self.horizontalLayout.addWidget(self.b14)
        self.b15 = QtWidgets.QLabel(self.bc1)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.b15.setFont(font)
        self.b15.setStyleSheet("background-color: white;")
        self.b15.setAlignment(QtCore.Qt.AlignCenter)
        self.b15.setObjectName("b15")
        self.horizontalLayout.addWidget(self.b15)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout.addWidget(self.bc1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pass_button = QtWidgets.QPushButton(CapTouchDialog)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.pass_button.setFont(font)
        self.pass_button.setAutoDefault(False)
        self.pass_button.setObjectName("pass_button")
        self.horizontalLayout_4.addWidget(self.pass_button)
        self.fail_button = QtWidgets.QPushButton(CapTouchDialog)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        self.fail_button.setFont(font)
        self.fail_button.setAutoDefault(False)
        self.fail_button.setObjectName("fail_button")
        self.horizontalLayout_4.addWidget(self.fail_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(CapTouchDialog)
        QtCore.QMetaObject.connectSlotsByName(CapTouchDialog)

    def retranslateUi(self, CapTouchDialog):
        _translate = QtCore.QCoreApplication.translate
        CapTouchDialog.setWindowTitle(_translate("CapTouchDialog", "Dialog"))
        self.label_8.setText(_translate("CapTouchDialog", "DUT2"))
        self.b21.setText(_translate("CapTouchDialog", "Mute"))
        self.b22.setText(_translate("CapTouchDialog", "V+"))
        self.b23.setText(_translate("CapTouchDialog", "Play"))
        self.b24.setText(_translate("CapTouchDialog", "V-"))
        self.b25.setText(_translate("CapTouchDialog", "BT"))
        self.label_6.setText(_translate("CapTouchDialog", "DUT1"))
        self.b11.setText(_translate("CapTouchDialog", "Mute"))
        self.b12.setText(_translate("CapTouchDialog", "V+"))
        self.b13.setText(_translate("CapTouchDialog", "Play"))
        self.b14.setText(_translate("CapTouchDialog", "V-"))
        self.b15.setText(_translate("CapTouchDialog", "BT"))
        self.pass_button.setText(_translate("CapTouchDialog", "PASS"))
        self.fail_button.setText(_translate("CapTouchDialog", "FAIL"))
