# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 509)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setContentsMargins(24, 24, 24, 24)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.container = QtWidgets.QWidget(self.centralwidget)
        self.container.setStyleSheet("QWidget#container{background-color:#FFFFFF}")
        self.container.setObjectName("container")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.cCodeSelectMenu = QtWidgets.QComboBox(self.container)
        self.cCodeSelectMenu.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.cCodeSelectMenu.setFont(font)
        self.cCodeSelectMenu.setVisible(False)
        self.cCodeSelectMenu.setStyleSheet("")
        self.cCodeSelectMenu.setObjectName("cCodeSelectMenu")
        self.cCodeSelectMenu.addItem("")
        self.cCodeSelectMenu.addItem("")
        self.cCodeSelectMenu.addItem("")
        self.cCodeSelectMenu.addItem("")
        self.cCodeSelectMenu.addItem("")
        self.horizontalLayout_2.addWidget(self.cCodeSelectMenu)
        self.langSelectMenu = QtWidgets.QComboBox(self.container)
        self.langSelectMenu.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.langSelectMenu.setFont(font)
        self.langSelectMenu.setStyleSheet("")
        self.langSelectMenu.setObjectName("langSelectMenu")
        self.langSelectMenu.addItem("")
        self.langSelectMenu.addItem("")
        self.langSelectMenu.addItem("")
        self.langSelectMenu.addItem("")
        self.horizontalLayout_2.addWidget(self.langSelectMenu)
        self.checkBoxEngMode = QtWidgets.QCheckBox(self.container)
        self.checkBoxEngMode.setMaximumSize(QtCore.QSize(582, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        self.checkBoxEngMode.setFont(font)
        self.checkBoxEngMode.setObjectName("checkBoxEngMode")
        self.horizontalLayout_2.addWidget(self.checkBoxEngMode)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.logo = QtWidgets.QLabel(self.container)
        self.logo.setMinimumSize(QtCore.QSize(100, 50))
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.horizontalLayout_2.addWidget(self.logo)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.hboxPorts = QtWidgets.QHBoxLayout()
        self.hboxPorts.setSpacing(6)
        self.hboxPorts.setObjectName("hboxPorts")
        self.verticalLayout.addLayout(self.hboxPorts)
        self.splitter_2 = QtWidgets.QSplitter(self.container)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.table_view = TableView(self.splitter_2)
        self.table_view.setStyleSheet("b")
        self.table_view.setObjectName("table_view")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.edit1 = QtWidgets.QPlainTextEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        self.edit1.setFont(font)
        self.edit1.setObjectName("edit1")
        self.edit2 = QtWidgets.QPlainTextEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        self.edit2.setFont(font)
        self.edit2.setObjectName("edit2")
        self.verticalLayout.addWidget(self.splitter_2)
        self.pushButton = QtWidgets.QPushButton(self.container)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("padding:10px")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addWidget(self.container)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cCodeSelectMenu.setItemText(0, _translate("MainWindow", "US"))
        self.cCodeSelectMenu.setItemText(1, _translate("MainWindow", "Canada"))
        self.cCodeSelectMenu.setItemText(2, _translate("MainWindow", "EU"))
        self.cCodeSelectMenu.setItemText(3, _translate("MainWindow", "ANZ"))
        self.cCodeSelectMenu.setItemText(4, _translate("MainWindow", "EU/P2"))
        self.langSelectMenu.setItemText(0, _translate("MainWindow", "en_US"))
        self.langSelectMenu.setItemText(1, _translate("MainWindow", "zh_TW"))
        self.langSelectMenu.setItemText(2, _translate("MainWindow", "zh_CN"))
        self.langSelectMenu.setItemText(3, _translate("MainWindow", "vi"))
        self.checkBoxEngMode.setText(_translate("MainWindow", "Engineering mode"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Total mac address :</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Remaining mac address :</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
from view.myview import TableView
